services:

  postgres:
    image: postgres:16

    env_file:
      - .env

    container_name: ml-postgres

    environment:
      POSTGRES_DB: housing
      POSTGRES_USER: mluser
      POSTGRES_PASSWORD: mlpassword

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  loader:
    build: .

    container_name: ml-loader

    command: python app/load_data.py

    env_file:
      - .env

    depends_on:
      - postgres


  api:
    build: .

    env_file:
      - .env

    container_name: ml-api

    ports:
      - "8000:8000"

    volumes:
      - ./models:/app/models

    depends_on:
      - postgres
  
  trainer:
    build: .

    env_file:
      - .env

    container_name: ml-trainer

    command: python app/train.py

    depends_on:
      - postgres


volumes:
  postgres_data: